apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-prod

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/hpa-patch.yaml

configMapGenerator:
  - name: fintech-config
    behavior: merge
    literals:
      - APP_ENV=production
      - LOG_LEVEL=warn
