apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-service.fullname" . }}-secret
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
