apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/hpa-patch.yaml

configMapGenerator:
  - name: fintech-config
    behavior: merge
    literals:
      - APP_ENV=staging
      - LOG_LEVEL=info
