apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/hpa-patch.yaml

configMapGenerator:
  - name: fintech-config
    behavior: merge
    literals:
      - APP_ENV=development
      - LOG_LEVEL=debug
