apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fintech-mobile-banking
  namespace: fintech

resources:
  - namespace.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - frontend/pdb.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/serviceaccount.yaml
  - backend/configmap.yaml
  - backend/hpa.yaml
  - backend/pdb.yaml
  - backend/ingress.yaml
  - configmap.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: fintech-mobile-banking
  app.kubernetes.io/managed-by: kustomize
